// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: markfeedfetched.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const markFeedFetched = `-- name: MarkFeedFetched :exec
UPDATE feeds
SET updated_at = $2 , last_fetched_at = $2
WHERE id = $1
`

type MarkFeedFetchedParams struct {
	ID        uuid.UUID
	UpdatedAt sql.NullTime
}

func (q *Queries) MarkFeedFetched(ctx context.Context, arg MarkFeedFetchedParams) error {
	_, err := q.db.ExecContext(ctx, markFeedFetched, arg.ID, arg.UpdatedAt)
	return err
}
